# syntax=docker/dockerfile:1
FROM python:alpine

WORKDIR /app

COPY requirements.txt .
RUN apk add --no-cache build-base sqlite
RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt
COPY . .
# STEP4-4では以下は変更しない
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0" , "--port", "9000"]
